#ifndef ENGINEGL_GLOBAL_H
#define ENGINEGL_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(ENGINEGL_LIBRARY)
#  define ENGINEGLSHARED_EXPORT Q_DECL_EXPORT
#else
#  define ENGINEGLSHARED_EXPORT Q_DECL_IMPORT
#endif

#endif // ENGINEGL_GLOBAL_H
